In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket indexing and Selection
Start counting from 0

In [5]:
arr[8]

8

In [8]:
arr[1:5]
# 5th element is not included.

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr1 = np.array([2,3,4,6,7,9,10,12,13,14,45])
arr1

array([ 2,  3,  4,  6,  7,  9, 10, 12, 13, 14, 45])

In [12]:
arr1[0]

2

In [14]:
arr1[0:5]

array([2, 3, 4, 6, 7])

In [15]:
arr1[0:6:2]

array([2, 4, 7])

## Broadcasting

In [16]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr
# Original array also changed. This avoids memory problem

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
# To get copy of it
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)