In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket indexing and Selection
Start counting from 0

In [5]:
arr[8]

8

In [8]:
arr[1:5]
# 5th element is not included.

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr1 = np.array([2,3,4,6,7,9,10,12,13,14,45])
arr1

array([ 2,  3,  4,  6,  7,  9, 10, 12, 13, 14, 45])

In [12]:
arr1[0]

2

In [14]:
arr1[0:5]

array([2, 3, 4, 6, 7])

In [15]:
arr1[0:6:2]

array([2, 4, 7])

## Broadcasting

In [16]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr
# Original array also changed. This avoids memory problem

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
# To get copy of it
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

In [26]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[1]

array([20, 25, 30])

In [28]:
arr_2d[1][0]
# 1 = row and 0 = column

20

In [29]:
arr_2d[1,0]

20

In [31]:
arr_2d[:2,1:]
# 0 and 1 row , 1 and 2 column

array([[10, 15],
       [25, 30]])

In [33]:
arr_2d[:1,:2]
# 0 row and 0,1 column

array([[ 5, 10]])

In [34]:
arr_2d[2]
# Last row

array([35, 40, 45])

In [36]:
arr_2d[:,2]
# Last column

array([15, 30, 45])

## Fancy Indexing

In [55]:
arr2d = np.zeros((10,10))
arr2d
# 10 rows and 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
arr2d.shape[1]
# Number of columns


10

In [47]:
arr_length = arr2d.shape[1]

In [59]:
for i in arr_length:
    print(i)

# because only 10 in not iterable. You need to have range form 0 to 9 to iterate through it.

TypeError: 'int' object is not iterable

In [57]:
for i in range(arr_length):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [58]:
range(arr_length)

range(0, 10)

In [63]:
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [64]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [65]:
arr2d[[6,4,7,3]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

## Selection

In [66]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
bool_arr = arr>4

In [69]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [70]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
x =2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])