## The basics
Numpy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In Numpy dimensions are called axes.

E.g. the array for the coordinates of a point in 3D space, [1,2,1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3

The first axis (axis 0) corresponds to the outermost level of nesting or the rows in the array. It indeed contains 2 arrays, so its length is 2.
The second axis (axis 1) corresponds to the innermost level or the elements within each row. Each row contains 3 elements, hence its length is 3.
So,The first axis refers to the outer brackets (rows) and the second axis refers to the inner brackets (elements within each row).

In [1]:
[[1.,0.,0.],
 [0.,1.,2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

Numpy's array class is called "ndarray". It is also known by the alias "array". The more imporatnt attributes of an "ndarray" object are:

1) ndarray.ndim
        the number of axes (dimensions) of the array

2) ndarray.shape
        the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimensions. For a matrix with "n" rows and "m" columns, "shape" will be (n,m). The length of the "shape" tuple is therefore the number of axes, "ndim".

3) ndarray.size
        the total number of elements of the array. This is equal to the product of the elements of "shape" (n * m).

4) ndarray.dtype
        an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own.

5) ndarray.itemsize
        the size in bytes of each element of the array. E.g., an array of elements of type "float64" has "itemsize" 8 (=64/8), while one of type "complex32" has "itemsize" 4 (=32/4).

6) ndarray.data
        the buffer contaning the actual elements of the array.

In [2]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype

dtype('int64')

In [6]:
a.size #(3 * 5)

15

In [7]:
type(a)

numpy.ndarray

## Array Creation
There are several ways to create arrays.

In [8]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [9]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, Numpy offers several functions to create arrays with initial placeholder content. 

The function "zeros" creates an array full of zeros, the function "ones" creates an array full of ones, and the function "empty" creates an array whose initial content is random and depends on the state of the memory.

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

let's break down below exmaple of 3-D array.
1) This array has 3 axes or dimensions
2) Axis 0: It has length of 2. This corresponds to the outermost level or the first dimension, which contains 2 arrays
3) Axis 1: It has a length of 3. This corresponds to the second dimension, which represents the rows within each array. Each array contains 3 rows
4) Axis 2: It has length of 4. This corresponds to the intermost level or the third dimension, which represents the elements within each row. Each row contains 4 elements. 

In [14]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides the "arange" function which is analogous to the python built-in "range", but returns an array. 

In [16]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [18]:
np.arange(0,2,0.3) # accepts float arguments also. 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When "arange" is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function "linespace" that receives as an argument the number of elements that we want, instead of the step.

In [19]:
from numpy import pi 
np.linspace(0,2,9)  # 9 numbers from 0

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
x = np.linspace(0, 2 * pi, 100) # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

## Printing arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

-- the last axis is printed from left to right

-- the second-to-last is printed from top to bottom

-- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [23]:
a = np.arange(6)  # 1D array
a

array([0, 1, 2, 3, 4, 5])

In [25]:
b = np.arange(12).reshape(4,3) # 2D array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
c = np.arange(24).reshape(2,3,4) # 3D array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Baisc operations
Arithmetic operators on array apply elementwise. A new array is created and filled with the result. 

In [28]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b 
c

array([20, 29, 38, 47])

In [29]:
b ** 2

array([0, 1, 4, 9])

In [30]:
a < 35

array([ True,  True, False, False])

In [31]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

Unlike in many matrix languages, the product operator "*" operates elementwise in NumPy arrays. The matrix product can be performed using "@" operator or "dot" function or method

In [32]:
A = np.array([[1,1],
             [0,1]])

B = np.array([[2,0],
              [3,4]])

A * B      # elementwise product

array([[2, 0],
       [0, 4]])

In [33]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [34]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

In [36]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [37]:
rg = np.random.default_rng(1)  # create instance of default random number generator

a = rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [38]:
a.sum()

3.290252281866131

In [39]:
a.min()

0.14415961271963373

In [40]:
a.max()

0.9504636963259353

In [41]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b.sum(axis=0)  # sum of each column

array([12, 15, 18, 21])

In [43]:
b.min(axis=1)  # min of each row

array([0, 4, 8])

In [45]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal functions
Numpy provides familiar mathematical functions such as sin, cos, and exp. In Numpy, these are called "universal functions" (ufunc). Within Numpy, these functions operate elementwise on an array, producing an array as output.

In [46]:
B = np.arange(3)
B

array([0, 1, 2])

In [47]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [48]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

## Indexing, slicing and iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other python sequences.

In [51]:
a = np.arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [52]:
a[2]

8

In [53]:
a[2:5]

array([ 8, 27, 64])

In [55]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [56]:
a[::-1] # reversed

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [57]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
